### ISSUE TITLE
Managing deployments with differing models

### ISSUE THREAD

**Issue by L4rryFisherman** [andredewes/apim-aoai-smart-loadbalancing#2]
Thank you a lot for this resource and the detailed setup instructions!

Can you recommend an approach for a case where the model availability differs per region/deployment?
e.g.
```
us-east: gpt-35-turbo, gpt-35-turbo16k, gpt-4
us-west: gpt-35-turbo, gpt-35-turbo16k
europe-west: gpt-4
```

Would the best way to handle this be to create an APIs entry (and xml) per model, or can it be handled with a single xml?

**Comment by andredewes** [comment]
In this case, you can try to modify the policy to include the full URL of your deployment:

**Comment by andredewes** [comment]
@L4rryFisherman 
As general guideline I don't recommend mixing models/versions because it can behave weirdly for your applications. Acknowledging that, there is a way to completely ignore what URL the client app is sending and rewrite everything from the APIM policy perspective. Here's how to do it:

Include the full URL of your deployment:

```
JArray backends = new JArray();
backends.Add(new JObject()
{
    { "url", "https://andre-openai-eastus.openai.azure.com/openai/deployments/gpt35turbo/chat/completions?api-version=2023-07-01-preview" },
    { "priority", 1},
    { "isThrottling", false }, 
    { "retryAfter", DateTime.MinValue } 
});

```

In the last line of the <inbound> section, add this snippet to overwrite the incoming path from your client app:

`<rewrite-uri template="?" copy-unmatched-params="false" />`

And finally, just change this line to remove the "+ /openai" concatenation from the original policy when setting the backend url:

`<set-variable name="backendUrl" value="@(((JObject)((JArray)context.Variables["listBackends"])[(Int32)context.Variables["backendIndex"]]).Value<string>("url"))" />`

In this way you can mix even GPT4 and GPT 3.5 within the same load balancing pool. Just remeber that any extra parameter or path coming from your applications will be totally overriden by whatever you set in the URLs above.

**Comment by L4rryFisherman** [comment]
Appreciate the detailed response!

To confirm, best practice is to create an xml per model+version+api_version, so for the example above it would be:
`1. gpt-35-turbo pool`
```
{... { "url", "https://andre-openai-eastus.openai.azure.com/" },
    ...},
{... { "url", "https://andre-openai-westus.openai.azure.com/" },
    ...},
```
`2. gpt-35-tubo-16k pool`
```
{... { "url", "https://andre-openai-eastus.openai.azure.com/" },
    ...},
{... { "url", "https://andre-openai-westus.openai.azure.com/" },
    ...},
```
`3. gpt-4 pool`
```
{... { "url", "https://andre-openai-eastus.openai.azure.com/" },
    ...},
{... { "url", "https://andre-openai-westeurope.openai.azure.com/" },
    ...},
```
Where then`1. gpt-35-turbo pool` and `2. gpt-35-tubo-16k pool` may be combined in this example, since the model+versions are the same. And we cannot do something to the effect of:
`Combined pool`
```
{... { "url", "https://andre-openai-eastus.openai.azure.com/" },
    "models": ["gpt-35-turbo", "gpt-35-turbo16k", "gpt-4"]
    ...},
    {... { "url", "https://andre-openai-westus.openai.azure.com/" },
    "models": ["gpt-35-turbo", "gpt-35-turbo16k"]
    ...},
{... { "url", "https://andre-openai-westeurope.openai.azure.com/" },
    "models": ["gpt-4"]
    ...},
```

Correct?

**Comment by andredewes** [comment]
Correct. The original policy sample works well keeping the same model+version+api_version in the backend pools. If you would like to have a separate set, it would be better to create another API endpoint in APIM with a different XML.

**Comment by L4rryFisherman** [comment]
Perfect, thank you!
